import openai
from typing import List, Dict
import json

class StoryProcessor:
    def __init__(self):
        self.plots = []
        
    def cluster_plots(self, plots: List[Dict[str, str]]) -> List[Dict]:
        """使用 GPT 將相似的情節分群"""
        
        # 準備情節列表
        plot_text = "\n".join([f"{i+1}. {p['plot']}" for i, p in enumerate(plots)])
        
        prompt = f"""
        Please analyze these story plots and group similar ones together.
        Return the result as JSON format with groups and their plot numbers.
        
        Plots:
        {plot_text}
        
        Format:
        {{
            "groups": [
                {{
                    "theme": "theme description",
                    "plot_indices": [1, 3, 5]
                }}
            ]
        }}
        """
        
        try:
            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are a story analyst."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=500
            )
            
            result = json.loads(response.choices[0].message.content)
            return result['groups']
            
        except Exception as e:
            print(f"Clustering error: {e}")
            # 如果失敗，返回所有情節作為一個群組
            return [{
                "theme": "All plots",
                "plot_indices": list(range(1, len(plots) + 1))
            }]
    
    def format_to_markdown(self, story: str, metadata: Dict) -> str:
        """將故事格式化為 Markdown"""
        markdown = f"""# {metadata.get('title', 'Generated Story')}

**Generated by:** {metadata.get('model', 'Unknown Model')}  
**Date:** {metadata.get('date', '')}  
**Based on plot:** {metadata.get('plot', '')}

---

{story}

---

*This story was generated using AI models.*
"""
        return markdown
